### PR TITLE
Fix «local variable 'inboxuids' referenced before assignment» when calling --teachonly

### PR DESCRIPTION
**Pull request by dantefff**
If isbg is called with --teachonly option it complains with the following error:
Traceback (most recent call last):
  File "isbg/isbg.py", line 598, in <module>
    partialrun)
  File "isbg/isbg.py", line 583, in filter_uids
    uids = [u for u in inboxuids if u not in pastuids]
UnboundLocalError: local variable 'inboxuids' referenced before assignment

Defining inboxuids as an empty list in case we are in --teachonly solves the issue

### CODE REVIEW

**Comment by dantefff** [comment]
There are more errors in --teachonly case. In fact I faced another bug: If an unexpected error raises in the code, the lockfile is not deleted. 
I don't know towards where are you going in this branch, if I understood right you plan to make a main() function. In this case this function should have a finally block where if the file was created in this execution it has to be deleted. In case your plan is to stay with a script-like structure (linear execution from the beginning), all the code should be inside a try and a finally must be called to make the cleanup.
PD: Sorry for my english

**Comment by dantefff** [comment]
Discard this pull request please. I have been taking a deeper look into code and I have make major code changes.
Please if you want take a look at my branch since there were major bugs in your code (specially the one that only processes first email)
Sorry for making it in a single huge commit but I was in a hurry. If you want info about it just ask.

**Comment by baldurmen** [comment]
Hmm, I'm not sure I get what you meant by all this... The goal of the v.1.01 was to move everything to functions and stop having all the code in a huge block.

I know it's not perfect (I haven't had time to look into that this weeks sadly), but IMHO it's the first step in code cleaning.

You want me to close this pull?

**Comment by dantefff** [comment]
Yes please, close this pull request.

I know it is the first step to do code cleaning. This is a good improve in code quality. First of all I don't use to code in python so I may be wrong in every line I write below this :-)

I have found some major bugs in the actual code. These are the ones that I have found and I have fixed in my fork (you can diff with it to take a deeper look):
- In the function «check_if_spam» the return statement is inside the for loop. It shouldn't becase the way it is now it exits on first spam found.
- The cleaning code «removelock(lockfilename)» should be in a finally or something like that. I put everything inside a try and called the cleaning in the finally but I think that the beauty way is to maka a main() function (see [Why use def main()?](http://stackoverflow.com/questions/4041238/why-use-def-main) ) Something like that:
  `def main():
  try:
      do the job
  finally:
      do the cleanup`

If this is not done in any of those ways, the lock file will not be removed on an error and therefore the script will not run until the lock file expires.
- With --teachonly option the «filter_uids» function does not initialize the list inboxuids, so it fails in the line «uids = [u for u in inboxuids if u not in pastuids]»

I think there are more minor issues with the use of global vars but I can not remember at the moment.

PD: I have made comments in my initial commit befor the fork:
[https://github.com/dantefff/isbg/commit/2dbd541b966b866065ab6164822f3d78fc0d7abe](https://github.com/dantefff/isbg/commit/2dbd541b966b866065ab6164822f3d78fc0d7abe)

**Pull request closed without merging**
